#!/usr/bin/env python3
"""
Wave 4 equivalence check: compare the workspace projection
(`docs/governance/architecture-workspace-graph.yaml`) against the legacy
`docs/governance/architecture-graph.yaml` generated by
`gate/build_architecture_graph.py`.

The two YAMLs intentionally use different node IDs (workspace uses
saa.id like ADR-0146, MOD-AGENT-BUS, RULE-D-1; legacy uses short ids
like ADR-0146, agent-bus, Rule-D-1). The comparator normalises across
the renaming and reports:

  * Node type counts (workspace vs legacy)
  * Node-set overlap (canonical-id intersection / workspace-only / legacy-only)
  * Edge type counts
  * High-level health verdict

Wave 5 will tighten the verdict into a blocking gate after the W6 yaml
sunset eliminates the legacy generator. For W4 this script is informational
and helps reviewers see the projection is in the right ballpark.

Usage:
    python3 gate/lib/compare_workspace_to_legacy_graph.py
"""
from __future__ import annotations

import sys
from collections import Counter
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[2]
LEGACY = REPO / "docs" / "governance" / "architecture-graph.yaml"
WORKSPACE = REPO / "docs" / "governance" / "architecture-workspace-graph.yaml"


def normalise_id(raw: str) -> str:
    """Canonicalise IDs so workspace and legacy ids align where possible.

    Workspace: ADR-0146, RULE-D-1, MOD-AGENT-BUS, PRINCIPLE-P-A, CAP-RUN-LIFECYCLE
    Legacy:    ADR-0146, Rule-D-1, agent-bus,     P-A,           run_lifecycle
    """
    if raw is None:
        return ""
    s = raw.strip()
    # Strip common prefixes the workspace adds for typed identifiers.
    for prefix in ("RULE-", "MOD-", "PRINCIPLE-", "CAP-", "FP-", "GEN-MOD-",
                   "SPI-", "ENF-", "TEST-", "SURFACE-"):
        if s.startswith(prefix):
            return s[len(prefix):].lower().replace("-", "_").replace(".", "_")
    # ADR ids and others normalise to lowercase.
    return s.lower().replace("-", "_").replace(".", "_")


def load(path: Path) -> dict:
    if not path.is_file():
        return {}
    return yaml.safe_load(path.read_text(encoding="utf-8")) or {}


def main() -> int:
    workspace = load(WORKSPACE)
    if not workspace:
        print(f"FAIL: workspace projection not found at {WORKSPACE}", file=sys.stderr)
        return 2

    legacy = load(LEGACY)
    if not legacy:
        print(f"WARN: legacy graph not found at {LEGACY}; cannot compare", file=sys.stderr)
        return 0

    workspace_nodes = workspace.get("nodes", []) or []
    legacy_nodes = legacy.get("nodes", []) or []

    workspace_types = Counter(n.get("type") for n in workspace_nodes)
    legacy_types = Counter(n.get("type") for n in legacy_nodes)

    print(f"Workspace projection: {len(workspace_nodes)} nodes / {len(workspace.get('edges', []))} edges")
    print(f"Legacy graph:         {len(legacy_nodes)} nodes / {len(legacy.get('edges', []))} edges")
    print()
    all_types = sorted(set(workspace_types) | set(legacy_types))
    print(f"{'type':<26} {'workspace':>10} {'legacy':>10}  delta")
    for t in all_types:
        ws = workspace_types.get(t, 0)
        lg = legacy_types.get(t, 0)
        print(f"  {t!s:<24} {ws:>10} {lg:>10}  {ws - lg:>+d}")
    print()

    # Node-set overlap by normalised id.
    ws_ids = {normalise_id(n.get("id")) for n in workspace_nodes}
    lg_ids = {normalise_id(n.get("id")) for n in legacy_nodes}
    overlap = ws_ids & lg_ids
    ws_only = ws_ids - lg_ids
    lg_only = lg_ids - ws_ids

    print(f"Node id overlap (normalised): {len(overlap)} shared")
    print(f"  workspace-only ids: {len(ws_only)}")
    print(f"  legacy-only ids:    {len(lg_only)}")

    # Health verdict — at W4 this is informational, not blocking.
    overlap_ratio = (len(overlap) / max(len(lg_ids), 1)) * 100
    print()
    print(f"Verdict: {overlap_ratio:.1f}% of legacy nodes are present in the workspace projection.")
    if overlap_ratio < 30:
        print("WARN: less than 30% overlap — projection may be missing major node classes")
        return 1
    print("PASS: workspace projection covers a substantial fraction of the legacy graph.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
