package com.huawei.ascend.tools.architecture.facts;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Shared helper for fact-layer extractors (ADR-0154 / Rule G-15).
 *
 * <p>Every extractor MUST go through this writer so the output carries:
 * <ul>
 *     <li>The {@code _banner} field with the "DO NOT EDIT" wording on a
 *         line in the first 5 lines of the file (Rule G-15.c).</li>
 *     <li>The {@code _provenance} block (extractor id, extractor version,
 *         repo commit, schema version) — Rule G-15.b shared metadata.</li>
 *     <li>The {@code facts} array — each entry already shaped by the
 *         caller to satisfy the 8 required fields in
 *         architecture/facts/schema/fact.schema.yaml.</li>
 * </ul>
 *
 * <p>Determinism contract: output is sorted by fact_id; no live timestamps;
 * Jackson is configured for pretty-print with stable key ordering provided
 * by the caller's {@link LinkedHashMap}s. Newlines are LF.
 */
public final class FactWriter {

    private static final String SCHEMA_VERSION = "1";

    private FactWriter() {
    }

    public static void write(
            Path outputFile,
            String extractor,
            String extractorVersion,
            String repoCommit,
            List<Map<String, Object>> facts) throws IOException {
        Map<String, Object> document = new LinkedHashMap<>();
        document.put("_banner",
                "DO NOT EDIT — generated by " + extractor + " at commit " + repoCommit
                        + ". See architecture/facts/README.md.");
        Map<String, Object> provenance = new LinkedHashMap<>();
        provenance.put("schema_version", SCHEMA_VERSION);
        provenance.put("extractor", extractor);
        provenance.put("extractor_version", extractorVersion);
        provenance.put("repo_commit", repoCommit);
        document.put("_provenance", provenance);
        document.put("facts", facts);

        ObjectMapper mapper = new ObjectMapper();
        mapper.enable(SerializationFeature.INDENT_OUTPUT);
        String json = mapper.writeValueAsString(document);
        // Force LF line endings even on Windows for byte-identical regen.
        json = json.replace("\r\n", "\n");
        if (!json.endsWith("\n")) {
            json = json + "\n";
        }
        Files.createDirectories(outputFile.getParent());
        Files.writeString(outputFile, json, StandardCharsets.UTF_8);
    }

    /**
     * Build a single fact entry with the 8 required provenance fields.
     * Caller passes in {@code observedValue} which is the fact's payload.
     */
    public static Map<String, Object> entry(
            String factId,
            String factKind,
            String sourceKind,
            String sourcePath,
            String sourceSymbol,
            String extractor,
            String extractorVersion,
            String repoCommit,
            Object observedValue) {
        Map<String, Object> fact = new LinkedHashMap<>();
        fact.put("fact_id", factId);
        fact.put("fact_kind", factKind);
        fact.put("source_kind", sourceKind);
        fact.put("source_path", sourcePath);
        if (sourceSymbol != null && !sourceSymbol.isEmpty()) {
            fact.put("source_symbol", sourceSymbol);
        }
        fact.put("extractor", extractor);
        fact.put("extractor_version", extractorVersion);
        fact.put("repo_commit", repoCommit);
        fact.put("observed_value", observedValue);
        return fact;
    }
}
