package com.huawei.ascend.tools.architecture.fragment;

import java.io.IOException;
import java.io.Writer;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Map;
import java.util.function.IntConsumer;

/**
 * Shared DSL fragment writer helpers. Every Wave 3 emitter writes its output
 * via this class so the DO-NOT-EDIT header, indentation, line endings, and
 * property-block layout stay byte-identical across emitters.
 */
public final class FragmentWriter {

    public static final String DO_NOT_EDIT_HEADER_PREFIX = "// DO NOT HAND EDIT";

    private FragmentWriter() {
    }

    /**
     * Open a writer that writes UTF-8, LF line endings, trailing newline, and the
     * standard DO-NOT-EDIT header naming the source path and emitter class.
     */
    public static StagedFragment open(Path output,
                                      String sourceDescription,
                                      String emitterClass,
                                      int elementCount) throws IOException {
        if (output.getParent() != null) {
            Files.createDirectories(output.getParent());
        }
        StringBuilder buf = new StringBuilder(8192);
        buf.append(DO_NOT_EDIT_HEADER_PREFIX).append(" — generated by ")
                .append(emitterClass).append(" from ").append(sourceDescription).append(".\n");
        buf.append("// Authority: ADR-0147 (Structurizr Workspace Authority). Gate: Rule G-13 (byte-identical regen).\n");
        buf.append("// Element count at emission: ").append(elementCount).append(".\n");
        buf.append("\n");
        return new StagedFragment(output, buf);
    }

    /** Property writer: emits a multi-line `properties { ... }` block. */
    public static void writeProperties(StringBuilder buf, Map<String, String> properties) {
        buf.append("    properties {\n");
        properties.forEach((k, v) -> buf.append("        \"")
                .append(escape(k)).append("\" \"").append(escape(v)).append("\"\n"));
        buf.append("    }\n");
    }

    /** Escape DSL string contents — strip CR, replace `"` with `'`, `{` with `(`, `}` with `)`. */
    public static String escape(String raw) {
        if (raw == null) {
            return "";
        }
        return raw.replace("\r", "")
                .replace("\n", " ")
                .replace("\"", "'")
                .replace("{", "(")
                .replace("}", ")");
    }

    /** Sanitize an identifier so it's a valid DSL identifier prefix. */
    public static String safeId(String raw) {
        if (raw == null || raw.isEmpty()) {
            return "_empty";
        }
        String s = raw.replaceAll("[^a-zA-Z0-9_]", "_");
        if (s.isEmpty() || !Character.isLetter(s.charAt(0))) {
            s = "_" + s;
        }
        return s;
    }

    /** Snapshot of a fragment being assembled; close() writes it to disk. */
    public static final class StagedFragment implements AutoCloseable {
        private final Path output;
        private final StringBuilder buf;

        StagedFragment(Path output, StringBuilder buf) {
            this.output = output;
            this.buf = buf;
        }

        public StringBuilder buf() {
            return buf;
        }

        public StagedFragment forEach(int count, IntConsumer body) {
            for (int i = 0; i < count; i++) {
                body.accept(i);
            }
            return this;
        }

        @Override
        public void close() throws IOException {
            String content = buf.toString().replace("\r\n", "\n");
            if (!content.endsWith("\n")) {
                content = content + "\n";
            }
            Files.writeString(output, content, StandardCharsets.UTF_8);
        }
    }

    /** Single-string-out variant — no Path; returns the would-be content. */
    public static String render(StringBuilder buf) {
        String content = buf.toString().replace("\r\n", "\n");
        if (!content.endsWith("\n")) {
            content = content + "\n";
        }
        return content;
    }
}
