package com.huawei.ascend.tools.architecture;

import com.structurizr.Workspace;
import com.structurizr.model.Element;
import com.structurizr.model.Model;
import com.structurizr.model.Relationship;

import java.io.IOException;
import java.io.Writer;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;

/**
 * Wave 4 compatibility projection: emits a graph YAML derived from the parsed
 * Structurizr workspace. The shape mirrors {@code docs/governance/architecture-graph.yaml}
 * (`nodes`, `edges` with `id`/`type`) so downstream graph consumers can read
 * the workspace projection without changing their parser.
 * <p>
 * Output is sorted alphabetically by node id / edge tuple. Determinism is the
 * foundation for Wave 4's byte-identical reverse-projection check.
 * <p>
 * Differences from the legacy {@code gate/build_architecture_graph.py} output:
 * <ul>
 *   <li>Node ids are the workspace {@code saa.id} (e.g. {@code MOD-AGENT-BUS},
 *       {@code RULE-D-1}, {@code ADR-0146}) — NOT the legacy short ids.
 *   <li>Edge types are the workspace {@code saa.rel} vocabulary (e.g.
 *       {@code operationalised_by}, {@code enforced_by}, {@code verifies}) —
 *       NOT every legacy edge type maps 1:1 (e.g. legacy {@code tested_by}
 *       reverses to workspace {@code verifies}).
 *   <li>Node count and edge count are reported in the header; Wave 5 will
 *       reconcile baseline_metrics with these.
 * </ul>
 */
public final class GraphProjectionWriter {

    public void write(Workspace workspace, Path output) throws IOException {
        Model model = workspace.getModel();

        List<Map<String, Object>> nodes = new ArrayList<>();
        for (Element el : model.getElements()) {
            Map<String, String> props = el.getProperties();
            String saaId = props.get("saa.id");
            if (saaId == null || saaId.isBlank()) {
                continue;  // skip native non-profile elements (no saa.id)
            }
            Map<String, Object> n = new LinkedHashMap<>();
            n.put("id", saaId);
            n.put("type", props.getOrDefault("saa.kind", "unknown"));
            nodes.add(n);
        }
        nodes.sort(Comparator.comparing(m -> (String) m.get("id")));

        List<Map<String, Object>> edges = new ArrayList<>();
        for (Relationship rel : model.getRelationships()) {
            Map<String, String> srcProps = rel.getSource().getProperties();
            Map<String, String> dstProps = rel.getDestination().getProperties();
            String srcId = srcProps.get("saa.id");
            String dstId = dstProps.get("saa.id");
            String relType = rel.getProperties().get("saa.rel");
            if (srcId == null || dstId == null || relType == null) {
                continue;
            }
            Map<String, Object> e = new LinkedHashMap<>();
            e.put("src", srcId);
            e.put("dst", dstId);
            e.put("type", relType);
            edges.add(e);
        }
        edges.sort(Comparator.<Map<String, Object>, String>comparing(m -> (String) m.get("src"))
                .thenComparing(m -> (String) m.get("dst"))
                .thenComparing(m -> (String) m.get("type")));

        if (output.getParent() != null) {
            Files.createDirectories(output.getParent());
        }

        try (Writer w = Files.newBufferedWriter(output, StandardCharsets.UTF_8)) {
            w.append("# DO NOT HAND-EDIT -- generated by tools/architecture-workspace\n");
            w.append("# (com.huawei.ascend.tools.architecture.GraphProjectionWriter) from\n");
            w.append("# architecture/workspace.dsl — workspace-derived compatibility projection.\n");
            w.append("# Authority: ADR-0147.\n");
            w.append("#\n");
            w.append("# Schema: architecture-workspace-graph/v1\n");
            w.append("# Re-emit: bash gate/check_architecture_workspace.sh (W5+).\n");
            w.append("\n");
            w.append("version: 1\n");
            w.append("schema: architecture-workspace-graph/v1\n");
            w.append("authority: ADR-0147 (Structurizr Workspace Authority)\n");
            w.append("generator: tools/architecture-workspace/.../GraphProjectionWriter.java\n");
            w.append("workspace_source: architecture/workspace.dsl\n");
            w.append("node_count: ").append(String.valueOf(nodes.size())).append("\n");
            w.append("edge_count: ").append(String.valueOf(edges.size())).append("\n");
            w.append("nodes:\n");
            for (Map<String, Object> n : nodes) {
                w.append("- id: ").append((String) n.get("id")).append("\n");
                w.append("  type: ").append((String) n.get("type")).append("\n");
            }
            w.append("edges:\n");
            for (Map<String, Object> e : edges) {
                w.append("- src: ").append((String) e.get("src")).append("\n");
                w.append("  dst: ").append((String) e.get("dst")).append("\n");
                w.append("  type: ").append((String) e.get("type")).append("\n");
            }
        }
    }
}
